apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-prod
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 9.2.5    # ← encore plus conservateur (ancienne version stable)
    helm:
      valueFiles:
        - values-prod.yaml
    path: grafana/prod       # dossier contenant le values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
