apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-int
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Maxime-CLS/argocd-app-of-apps.git
    targetRevision: main
    path: argocd-app-of-apps/grafana/int
    helm:
      valueFiles:
        - values-int.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-int
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
