apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-dev
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 9.3.0   # ou la version que tu veux
    helm:
      valueFiles:
        - values-dev.yaml
    path: grafana/dev       # chemin relatif dans ton Git (uniquement pour values.yaml)
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
