adminUser: admin
adminPassword: intpass456

replicaCount: 3

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus.monitoring-prod.svc.cluster.local:9090
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki.monitoring-prod.svc.cluster.local:3100
        access: proxy

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: Prod Dashboards
        type: file
        options:
          path: /var/lib/grafana/dashboards/prod

dashboardsConfigMaps:
  prod-dashboards: "prod"

plugins:
  - grafana-piechart-panel
  - grafana-worldmap-panel
  - grafana-polystat-panel
